spring:
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/fitta}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1111}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          jdbc:
            lob:
              non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG












